version: "3.0"
services:
  db:
    image: postgres:14.1-alpine
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: ${PGDATA}
    restart: always
  app:
    image: anivaldocker/boardsapp
    build: .
    container_name: application
    ports:
      - ${PORT}:${PORT}
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
    restart: always
    volumes:
      - /Users/admin/Documents/rss-node/nodejs2021Q4-service:/app
      - /app/node_modules
      - storage:/app/data
    links:
      - db
volumes:
  storage: